### ISSUE TITLE
MT 940 Parsing Issue

### ISSUE THREAD

**Issue by maxhille** [mitch000001/go-hbci#13]
MT 940 messages are delimited by "<cr><lf>-". The message lines by "<cr><lf>". My account's history now (of course ;-) actually has a message line starting with "-" leading the parser into splitting/corrupting a message with subsequent (expected) message parsing failure.

I am looking into ways to fix this and would be happy about suggestions. My ideas so far:

1. The lexer needs more state (ie. 'I am within the Customer Info field right now, so "-" is not syntax')
2. Fix this somewhere in the encoding/charset conversions (http->hbci->swift). I tried to find info about the encoding specs but did not find clear answers.

What do you think?

**Comment by maxhille** [comment]
Here is a dump with should trigger the problem. I tried to build a use case to get a parser error but did not have enough time to understand the parser code enough yet. I hand-edited some stuff out mainly replacing numbers and some text characters for priavcy reaons. I hope by doing this I didnt break another part of the parser. Tell me if this doesn't work for you. I also inserted a Mardown-Enter after every original `\r\n`.

Note how the segment is delimited at the end `\r\n-` and how (at least as I suspect) the same parser condition triggers 'segment end' three lines above at a line starting with `-`

```
\r\n
:20:MT940-1803060458\r\n
:21:NONREF\r\n
:25:20040000/12345678EUR\r\n
:28C:0/13\r\n:60M:C170201EUR1234,56\r\n
:61:1702010201DR86,40NMSCNONREF//POS 8888888888\r\n
:86:005?20LASTSCHRIFT/BELAST.?888888888888 8888888884REFERE?22NZ HVV \r\n
A?23BO?24END-TO-END-REF.:?888888888888 8888888884?26CORE / MANDAT\r\n
SREF.:?27VMH008888880001?28GL\xc4UBIGER-ID:?29DE88888888888888888?32H\r\n
AMBURGER HOCHBAHN AG?60Ref. IL888888G8888888/6716\r\n
:61:1702010201DR24,00NMSCNONREF//POS 3409790600\r\n
:86:005?20LASTSCHRIFT/BELAST.?21110865 BEITRAG MITGLIED 888?228888?23\r\n
END-TO-END-REF.:?8888888888888ZV888888Z?25CORE / MANDATSREF.:?26EV\r\n
-000008888?27GL\xc4UBIGER-ID:?88DE88ZZZ8888888888?29Ref. IL888888G2\r\n
145077/1543?32SOME TEST-VEREIN E.V.\r\n
:62M:C170203EUR5378,36\r\n
-
```

**Comment by mitch000001** [comment]
Hey, should be fixed in version 0.1.2 https://github.com/mitch000001/go-hbci/releases/tag/v0.1.2 Can you please try it?

**Comment by mitch000001** [comment]
@maxhille meh, found another bug within the new implementation. Please try version [v0.1.3](https://github.com/mitch000001/go-hbci/releases/tag/v0.1.3).

**Comment by mitch000001** [comment]
@maxhille is it possible for you to verify that it is fixed so that I can close this issue?

**Comment by maxhille** [comment]
sorry, I am on vacation right now and will not be able to test it for another week or so

**Comment by mitch000001** [comment]
oh, sorry for disturbing you. Take your time, no hurry :)

**Comment by maxhille** [comment]
I just tested it but it does not work yet. I am getting another error which is probably related:

```Error while decrypting message: Malformed decrypted message bytes: strconv.ParseFloat: parsing "5378.36\r\n-": invalid syntax```

**Comment by mitch000001** [comment]
@maxhille did you test v0.1.3? Because v0.1.2 had the mentioned bug whereas the new version should not.

**Comment by maxhille** [comment]
Sorry it took so long, but I got another dump which fails for v0.1.3

```
:20:MT940-1804300355
:21:NONREF
:25:20012345/112233445EUR
:28C:0/2
:60M:C170203EUR1234,56
:61:1702030203DR1,00NMSCNONREF//POS 3416383187
:86:005?20LASTSCHRIFT/BELAST.?21SEPADDDD00009999999-01 DRI?22VENOW 9
3?2350790427 IHRE BILLPAYZAHLUN?24G 0055 3?555 555 555 555 WWW.BI
LLPAY.D?26E?27END-TO-END-REF.:?28SEPADDDD00009999999-01?29CORE /
 MANDATSREF.:?32BILLPAY GMBH?12345556667-1-12345678?61GLÄUBIGER-ID
:?62DE19ZZZ00000999999?63Ref. I9999099B999999/280
:61:9909999203DR1000,00NMSCNONREF//POS 9999999999
:86:820?20ÜBERTRAG/ÜBERWEISUNG?21CBAEURXABCDEFG?22END-TO-END-REF.:?23
NICHT ANGEGEBEN?24Ref. H09999999999999/2?30ABCDEF22XXX?31EE99999
0999009999999?32COINBASE UK, LTD.
:62M:C170206EUR1234,56
-
```

As far as I understand it, the first custom/86-tag is extracted wrong. The following line (which begins with ":?62DE...") should still be part of the tag, but gets extracted into its own tag.

**Comment by mitch000001** [comment]
@maxhille I fixed the issue within [v0.1.5](https://github.com/mitch000001/go-hbci/releases/tag/v0.1.5). Please verify it.
Additionally I really want to thank you for your effort. It really helps to have breaking test data so that I can write failing tests accordingly 👍

**Comment by maxhille** [comment]
Looks good now, thanks!

**Comment by mitch000001** [comment]
:+1:👌
